apiVersion: apps/v1
kind: Deployment
metadata:
  name: gomoku-mongodb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gomoku-mongodb
  template:
    metadata:
      labels:
        app: gomoku-mongodb
    spec:
      containers:
      - name: gomoku-mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: "0.5"
            memory: "1Gi"
          limits:
            cpu: "1" 
            memory: "2Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: gomoku-mongodb-service
spec:
  selector:
    app: gomoku-mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP
